GET http://localhost:3000/home/post
Content-Type: application/json



###
POST http://localhost:3000/auth/signup
Content-Type: application/json 

{
    "firstName": "jean",
    "lastName": "michel",
    "email": "jm@orange.fr",
    "password": "jeanjean"
} 


###
POST http://localhost:3000/auth/login
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXJzIjoyMCwiaWF0IjoxNjMxMTQyMjQ0LCJleHAiOjE2MzEyMjg2NDR9.X_l8mxxpFNvUCgjoqaoAmopovmAVrTAJQi9A-1V5sZY


{
    "idUsers":20,
    "firstName": "jean",
    "lastName": "michel",
    "email": "jm@orange.fr",
    "password": "jeanjean"
} 


###
POST http://localhost:3000/home/post
Content-Type: application/json 


{     
        "idUser": 10,
 		"content": "salut la planète"
} 


###
DELETE  http://localhost:3000/home/post/31
Content-Type: application/json 



// COMMENTS

###
POST  http://localhost:3000/home/post/1
Content-Type: application/json 

{     
        "idUser": 12,
 		"content": "Bienvenue"
} 

###
GET  http://localhost:3000/home/post/10/comment
Content-Type: application/json 



###
DELETE  http://localhost:3000/home/comment/7
Content-Type: application/json 
