
###
POST http://localhost:3000/auth/signup
Content-Type: application/json 

{
    "firstName": "john",
    "lastName": "doe",
    "email": "jid@mail.fr",
    "password": "hey"
} 


###
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
      "email": "test@mail.fr",
    "password": "mariemarie"
} 

// POST
###
GET http://localhost:3000/home/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjQsImlhdCI6MTYzMTYzMjM5NCwiZXhwIjoxNjMxNzE4Nzk0fQ.YL7ZY9l_kqPRiqxsUJzDr5NKCdVv3jNBc3VmrihLIE4


###
POST http://localhost:3000/home/post
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjQsImlhdCI6MTYzMTYyODY4MywiZXhwIjoxNjMxNzE1MDgzfQ.c6ByQ-DO5gfob6bhdc_KijLkTkCM9ggif3abRd_sqCw

{       
        "idUser": 4,
 		"content": "hey!"
} 


###
DELETE  http://localhost:3000/home/post/21
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjQsImlhdCI6MTYzMTYzMjM5NCwiZXhwIjoxNjMxNzE4Nzk0fQ.YL7ZY9l_kqPRiqxsUJzDr5NKCdVv3jNBc3VmrihLIE4

{
    "idUser": 4
}


// COMMENTS

###
POST  http://localhost:3000/home/post/22
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjQsImlhdCI6MTYzMTM5Mjc2OCwiZXhwIjoxNjMxNDc5MTY4fQ.JdFWIJnvJNPvgdBL0FGYfi2LLG8roWCGstuKHoE_sSg

{     
        "idUser": 4,
 		"content": "je commente ce post"
} 

###
GET  http://localhost:3000/home/post/22/comment
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjQsImlhdCI6MTYzMTM5Mjc2OCwiZXhwIjoxNjMxNDc5MTY4fQ.JdFWIJnvJNPvgdBL0FGYfi2LLG8roWCGstuKHoE_sSg



###
DELETE  http://localhost:3000/home/comment/10
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjQsImlhdCI6MTYzMTM5Mjc2OCwiZXhwIjoxNjMxNDc5MTY4fQ.JdFWIJnvJNPvgdBL0FGYfi2LLG8roWCGstuKHoE_sSg

{
    "idUser": 4
}


//PROFIL
###
GET  http://localhost:3000/home/profil
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjQsImlhdCI6MTYzMTM5Mjc2OCwiZXhwIjoxNjMxNDc5MTY4fQ.JdFWIJnvJNPvgdBL0FGYfi2LLG8roWCGstuKHoE_sSg

###
GET  http://localhost:3000/home/profil/4
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjQsImlhdCI6MTYzMTY1NjY4MCwiZXhwIjoxNjMxNzQzMDgwfQ.4WFDcJZpVi0t6ardOSnH0MwbwLq7oJaO2okrHH81Z_A


###
PUT  http://localhost:3000/home/profil/2
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjQsImlhdCI6MTYzMTM5Mjc2OCwiZXhwIjoxNjMxNDc5MTY4fQ.JdFWIJnvJNPvgdBL0FGYfi2LLG8roWCGstuKHoE_sSg

{
        "idUser": 2,
        "lastName": "jean"
} 

###
DELETE  http://localhost:3000/home/profil/2
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjQsImlhdCI6MTYzMTM5Mjc2OCwiZXhwIjoxNjMxNDc5MTY4fQ.JdFWIJnvJNPvgdBL0FGYfi2LLG8roWCGstuKHoE_sSg

{
    "idUser": 2
} 